/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Entry {
  'id' : bigint,
  'entryType' : string,
  'date' : string,
  'description' : string,
  'timestamp' : Time,
  'category' : string,
  'amount' : number,
}
export type EntryId = bigint;
export interface FinanceSummary {
  'balance' : number,
  'totalIncome' : number,
  'totalExpenses' : number,
}
export interface Preferences {
  'geminiApiKey' : string,
  'language' : string,
  'darkMode' : boolean,
}
export interface Task {
  'id' : bigint,
  'title' : string,
  'date' : string,
  'user' : User,
  'completed' : boolean,
  'description' : string,
  'timestamp' : Time,
}
export type TaskId = bigint;
export type Time = bigint;
export type User = Principal;
export interface UserProfileView {
  'tasks' : Array<Task>,
  'name' : string,
  'email' : string,
  'preferences' : Preferences,
  'registrationTime' : Time,
  'finances' : Array<Entry>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Note {
  'id' : bigint,
  'title' : string,
  'body' : string,
  'folderId' : bigint,
  'tags' : Array<string>,
  'timestamp' : Time,
}
export interface Folder {
  'id' : bigint,
  'name' : string,
  'color' : string,
  'timestamp' : Time,
}
export interface Outfit {
  'id' : bigint,
  'name' : string,
  'occasion' : string,
  'description' : string,
  'photoUrl' : string,
  'tags' : Array<string>,
  'timestamp' : Time,
}
export interface ClothingItem {
  'id' : bigint,
  'name' : string,
  'category' : string,
  'photoUrl' : string,
  'timestamp' : Time,
}
export interface PlannerDayOutfit {
  'date' : string,
  'outfitId' : bigint,
}
export interface Routine {
  'id' : bigint,
  'name' : string,
  'timeOfDay' : string,
  'timestamp' : Time,
}
export interface RoutineCompletion {
  'date' : string,
  'completedRoutineIds' : Array<bigint>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createFinanceEntry' : ActorMethod<
    [number, string, string, string, string],
    Entry
  >,
  'createTask' : ActorMethod<[string, string, string], Task>,
  'deleteEntry' : ActorMethod<[EntryId], undefined>,
  'deleteTask' : ActorMethod<[TaskId], undefined>,
  'getAllEntries' : ActorMethod<[], Array<Entry>>,
  'getAllTasks' : ActorMethod<[], Array<Task>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfileView]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getSummary' : ActorMethod<[], FinanceSummary>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfileView]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listEntriesByType' : ActorMethod<[string], Array<Entry>>,
  'listTasksByDate' : ActorMethod<[string], Array<Task>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfileView], undefined>,
  'updatePreferences' : ActorMethod<[string, boolean, string], undefined>,
  'updateTask' : ActorMethod<[bigint, string, string, boolean], Task>,
  'createNote' : ActorMethod<[string, string, bigint, Array<string>], Note>,
  'updateNote' : ActorMethod<[bigint, string, string, bigint, Array<string>], Note>,
  'deleteNote' : ActorMethod<[bigint], undefined>,
  'getAllNotes' : ActorMethod<[], Array<Note>>,
  'createFolder' : ActorMethod<[string, string], Folder>,
  'deleteFolder' : ActorMethod<[bigint], undefined>,
  'getAllFolders' : ActorMethod<[], Array<Folder>>,
  'createOutfit' : ActorMethod<[string, string, string, string, Array<string>], Outfit>,
  'updateOutfit' : ActorMethod<[bigint, string, string, string, string, Array<string>], Outfit>,
  'deleteOutfit' : ActorMethod<[bigint], undefined>,
  'getAllOutfits' : ActorMethod<[], Array<Outfit>>,
  'createClothingItem' : ActorMethod<[string, string, string], ClothingItem>,
  'updateClothingItem' : ActorMethod<[bigint, string, string, string], ClothingItem>,
  'deleteClothingItem' : ActorMethod<[bigint], undefined>,
  'getAllClothingItems' : ActorMethod<[], Array<ClothingItem>>,
  'setPlannerDayOutfit' : ActorMethod<[string, bigint], PlannerDayOutfit>,
  'deletePlannerDayOutfit' : ActorMethod<[string], undefined>,
  'getPlannerDayOutfit' : ActorMethod<[string], [] | [PlannerDayOutfit]>,
  'getAllPlannerDayOutfits' : ActorMethod<[], Array<PlannerDayOutfit>>,
  'createRoutine' : ActorMethod<[string, string], Routine>,
  'updateRoutine' : ActorMethod<[bigint, string, string], Routine>,
  'deleteRoutine' : ActorMethod<[bigint], undefined>,
  'getAllRoutines' : ActorMethod<[], Array<Routine>>,
  'setRoutineCompletion' : ActorMethod<[string, Array<bigint>], RoutineCompletion>,
  'getAllRoutineCompletions' : ActorMethod<[], Array<RoutineCompletion>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
